import Foundation
import AroCommon

/// Read-through access to loudness generated by the library server. Playback must
/// never decode a file to manufacture missing canonical analysis: when the cached
/// server result is absent, normalized mode simply plays that track without gain.
actor LoudnessAnalysisService: LoudnessAnalyzing {
    private let repository: any LoudnessAnalysisRepository

    init(
        cacheURL _: URL? = nil,
        repository: any LoudnessAnalysisRepository
    ) {
        self.repository = repository
    }

    func cachedAnalysis(for song: Song) -> LoudnessAnalysis? {
        guard let key = song.fileFingerprint?.cacheKey else {
            return nil
        }
        return repository.analysis(
            fingerprint: key,
            algorithmVersion: LoudnessAnalysis.remoteAlgorithmVersion
        )
    }

    func analysis(for song: Song) async -> LoudnessAnalysis? {
        cachedAnalysis(for: song)
    }

    func analyzeInBackground(_: [Song]) async {}
}
